title: Kabar IndonesiaX
description: Kabar Terbaru dari IndonesiaX

url: https://dehamzah.com/indonesiax-blog
baseurl: "/indonesiax-blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Kabar Terbaru
   url: /index.html
 - title: Learner Stories
   url: /learner-stories
 - title: Kursus
   url: http://www.indonesiax.co.id/courses

social:
   twitter: IndonesiaX_News
   facebook: IndonesiaXNews
   email: info@indonesiax.co.id

google_analytics: "UA-58263416-1"
